config/routes.rb
Try::Application.routes.draw do

  resources :offers
  resources :users
  resources :addresses
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/contact', to: 'contacts#show'
  
  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'

  get "home/index"

   root :to => "home#index"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation # Always define accessible attributes in models. If not, every attr is accessible.
  has_secure_password
  
  has_many :microposts, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships
  
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: valid_email_regex },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 2}

  def feed
    Micropost.from_users_followed_by(self)
  end
  
  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end
  
  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :show, :edit, :update, :following, :followers]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    if @user.admin?
      @addresses_count = Address.count
    else
      @addresses_count = @user.addresses.count
    end
  end

  def new
    if current_user.nil?
      @user = User.new
    else
      flash[:notice] = "You already have an acoount"
      redirect_to(root_path)
    end
  end
  
  def create
    if current_user.nil?
      @user = User.new(params[:user])
      if @user.save
        sign_in @user
        flash[:success] = "Welcome to the Sample App!"
        redirect_to User.last #this is a hack User.last should be @user but that one always have id 0
      else
        render 'new'
      end
    else
      flash[:notice] = "You already have an acoount"
      redirect_to(root_path)
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    user = User.find(params[:id])
    if current_user == user
      flash[:notice] = "You cannot delete your self"
    else
      user.destroy
      flash[:success] = "User destroyed."
    end
    redirect_to users_path
  end
  
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  

end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.build(followed_id: @user.id),
              remote: true do |f| %> <!-- to make Ajax to work -->
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(@user),
             html: { method: :delete },
             remote: true do |f| %> <!-- to make Ajax to work -->
  <div class="actions"><%= f.submit "Unfollow" %></div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 30 %>
  <%= link_to user.name, user %>

	<% if (current_user?(user) && !current_user.admin?) || (current_user.admin? && !current_user?(user)) %>
    | <%= link_to "delete", user, method: :delete, confirm: "You sure?" %>
  	<% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, "Edit user" %> 
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'fields', f: f %>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for(@user) %>
  <%= link_to "change", "http://gravatar.com/emails", :target => "_blank" %><br/>
  <%= link_to 'New Address', new_address_path %>
</div>

app/views/users/index.html.erb
<% provide :title, 'All users' %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %> <!-- This iterates over @users and renders partial _user.html.erb -->
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'fields', f: f %>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<table class="profile">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user, size: 40 %>
        <%= @user.name %>
      </h1>
      <%= render 'follow_form' if signed_in? %>
      <% if @user.microposts.any? %>
        <table class="microposts">
          <%= render @microposts %>
        </table>
        <%= will_paginate @microposts %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %><br />
      <strong><%= link_to "Addresses", address_path(@user.id) %></strong> <%= @addresses_count %><br />
      <strong>Microposts</strong> <%= @user.microposts.count %>
      <%= render 'shared/stats' %>
    </td>
  </tr>
</table>

app/views/users/show_follow.html.erb
<table>
  <tr>
    <td class="main">
      <h1><%= @title %></h1>

      <% if @users.any? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate @users %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <strong>Microposts</strong> <%= @user.microposts.count %>
      <%= render 'shared/stats' %>
      <% unless @users.empty? %>
        <% @users.each do |user| %>
          <%= link_to gravatar_for(user, size: 30), user %>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>