config/routes.rb
Try::Application.routes.draw do

  resources :offers
  resources :users
  resources :addresses
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/contact', to: 'contacts#show'
  
  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'

  get "home/index"

   root :to => "home#index"

end

app/models/offer.rb
# == Schema Information
#
# Table name: offers
#
#  id          :integer(4)      not null, primary key
#  title       :string(255)
#  description :text
#  price       :float
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Offer < ActiveRecord::Base
  validates :description,  :presence => true
  validates :title, :presence => true, :length => { :minimum => 5 }
  validates :price, :presence => true
  validates :price, :numericality => true
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offers }
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    @offer = Offer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/new
  # GET /offers/new.json
  def new
    @offer = Offer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/1/edit
  def edit
    @offer = Offer.find(params[:id])
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(params[:offer])

    respond_to do |format|
      if @offer.save
        format.html { redirect_to offers_url, notice: 'Offer was successfully created.' }
        format.json { render json: @offer, status: :created, location: @offer }
      else
        format.html { render action: "new" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offers/1
  # PUT /offers/1.json
  def update
    @offer = Offer.find(params[:id])

    respond_to do |format|
      if @offer.update_attributes(params[:offer])
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
	<% if @offer.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>
		
		  <ul>
		  <% @offer.errors.full_messages.each do |msg| %>
		    <li><%= msg %></li>
		  <% end %>
		  </ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :title %><br />
		<%= f.text_field :title %>
 	</div>
 	<div class="field">
		<%= f.label :description %><br />
		<%= f.text_area :description %>
 	</div>
 	<div class="field">
		<%= f.label :price %><br />
		<%= f.text_field :price %>
 	</div>
 	<div class="actions">
		<%= f.submit %>
 	</div>
<% end %>

app/views/offers/edit.html.erb
<div id="header" class="clearfix shadow">
	<div id="sitetitle" class="clearfix">
		<h1><a href="/home/index.html">Editing offer</a></h1>
	</div>
</div>
	
<div id="content" class="clearfix shadow">
	<div id="sidebar" class="left">
		<div class="inner">
			<div id="nav" class="clearfix">
				<ul>
					<li>
						<%= link_to 'Show', @offer %> 
					</li>
					<li>
						<%= link_to 'Back', offers_path %>	
					</li>
				</ul>
			</div>			
		</div>
	</div>
	
	<div id="main" class="right">
		<%= render 'form' %>
	</div>
</div>

app/views/offers/index.html.erb
<div id="header" class="clearfix shadow">
	<div id="sitetitle" class="clearfix">
		<h1><a href="home/index.html">Offers List</a></h1>
	</div>
</div>

<p id="notice"><%= notice %></p>

<div id="content" class="clearfix shadow">
	<div id="sidebar" class="left">
		<div class="inner">
			<div id="nav" class="clearfix">
				<ul>
					<li>
						<%= link_to 'New Offer', new_offer_path %>
					</li>
				</ul>
			</div>
		</div>
	</div>
	
	<table>
	  <tr>
	    <th>Title</th>
	  </tr>
	
	<% @offers.each do |offer| %>
	  <tr>
	    <td><%= link_to offer.title, offer %></td>
	    <td>
		    <div id="nav" class="clearfix">
				<ul>
					<li>
						<%= link_to 'Edit', edit_offer_path(offer) %>
					</li>
					<li>
						<%= link_to 'Destroy', offer, confirm: 'Are you sure?', method: :delete %>
					</li>
				</ul>
			</div>   	
	    </td>
	  </tr>
	<% end %>
	</table>
</div>

app/views/offers/new.html.erb
<div id="header" class="clearfix shadow">
	<div id="sitetitle" class="clearfix">
		<h1><a href="/home/index.html">New Offer</a></h1>
	</div>
</div>

<div id="content" class="clearfix shadow">
	<div id="sidebar" class="left">
		<div class="inner">
			<div id="nav" class="clearfix">
				<ul>
					<li>
						<%= link_to 'Back', offers_path %>
					</li>
				</ul>
			</div>
		</div>
	</div>
	
	<div id="main" class="right">
		<%= render 'form' %>
	</div>
</div>

app/views/offers/show.html.erb
<div id="content" class="clearfix shadow">
	<div id="sidebar" class="left">
		<div class="inner">
			<div id="nav" class="clearfix">
				<ul>
					<li>
						<%= link_to 'Edit', edit_offer_path(@offer) %>
					</li>
					<li>
						<%= link_to 'Back', offers_path %>	
					</li>
				</ul>
			</div>
		</div>
	</div>
	
	<div id="main" class="right">
		<p id="notice"><%= notice %></p>
		<p>
		  <b>Title:</b>
		  <%= @offer.title %>
		</p>
		
		<p>
		  <b>Description:</b>
		  <%= @offer.description %>
		</p>
		
		<p>
		  <b>Price:</b>
		  <%= @offer.price %>
		</p>
	</div>
</div>